site_name: stock-market-analysis

theme:
    name: "material"

plugins:
    - mkdocstrings
    - autorefs
    - swagger-ui-tag
    - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - "Introduction": index.md
    - "Getting Started": getting_started.md
    - "Developer Guide": dev_commands.md
    - "Code Reference": reference.md
